name: Deployment workflow
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
        type: tag
      environment:
          description: 'Environment to run tests against'
          type: environment
          required: true
